version: "3.9"

services:
  api:
    container_name: s1_db
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - IS_COMPOSE=dockerdev
    depends_on:
      - db
      - migration
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14.4-alpine
    ports:
      - 5435:5432
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    env_file: .env
    volumes:
      - .:/code
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn typeorm migration:run -d src/data-source.ts'
    depends_on:
      - db

volumes:
  pgdata:
